# tests/test_crosstab.py

import pytest
import pandas as pd

# Import the function and schemas to be tested
from backend.app.analysis.crosstab import run
from backend.app.schemas import CrosstabAnalysis, Filter, ReportBlock, ColumnTransformation, Transformation

@pytest.fixture
def sample_df() -> pd.DataFrame:
    """Provides a DataFrame with categorical and delimited data for crosstab testing."""
    data = {
        'region':   ['NA', 'NA', 'EU', 'EU', 'ASIA', 'NA'],
        'product':  ['apple', 'orange', 'apple', 'orange', 'apple', 'apple'],
        'status':   ['active', 'active', 'inactive', 'active', 'active', 'inactive'],
        'tags':     ['A,B', 'C', 'B', 'A,C', 'A', 'C']
    }
    return pd.DataFrame(data)

# ==============================================================================
# 1. Basic Functionality Tests
# ==============================================================================

def test_crosstab_basic(sample_df):
    """Tests a standard crosstab without grouping or transformations."""
    step = CrosstabAnalysis(
        output_name="Region vs Product",
        index_column="region",
        column_to_compare="product"
    )
    result = run(sample_df, step)

    assert isinstance(result, ReportBlock)
    results_df = result.data.set_index('region') # Set index for easy lookup

    # Check specific cell values
    # NA has 2 'apple' and 1 'orange'
    assert results_df.loc['NA', 'apple'] == 2
    assert results_df.loc['NA', 'orange'] == 1
    # EU has 1 'apple' and 1 'orange'
    assert results_df.loc['EU', 'apple'] == 1
    # ASIA has 1 'apple' and 0 'orange'
    assert results_df.loc['ASIA', 'apple'] == 1
    assert results_df.loc['ASIA', 'orange'] == 0
    
    # Check totals generated by `margins=True`
    assert results_df.loc['All', 'All'] == 6 # Grand total

def test_crosstab_with_grouping(sample_df):
    """Tests that crosstab is calculated correctly for each subgroup."""
    step = CrosstabAnalysis(
        output_name="Grouped by Status",
        index_column="region",
        column_to_compare="product",
        group_by=["status"]
    )
    result = run(sample_df, step)
    results_df = result.data

    # Test the 'active' group
    active_df = results_df[results_df['Group'] == 'active'].set_index('region')
    # In 'active' status: NA has 1 apple, 1 orange. EU has 1 orange. ASIA has 1 apple.
    assert active_df.loc['NA', 'apple'] == 1
    assert active_df.loc['EU', 'orange'] == 1
    assert active_df.loc['All', 'All'] == 4 # Total for 'active' group

    # Test the 'inactive' group
    inactive_df = results_df[results_df['Group'] == 'inactive'].set_index('region')
    # In 'inactive' status: NA has 1 apple. EU has 1 apple.
    assert inactive_df.loc['NA', 'apple'] == 1
    assert inactive_df.loc['EU', 'apple'] == 1
    assert inactive_df.loc['All', 'All'] == 2 # Total for 'inactive' group

def test_crosstab_with_percentages(sample_df):
    """Tests the percentage calculation feature."""
    step = CrosstabAnalysis(
        output_name="Row Percentages",
        index_column="region",
        column_to_compare="product",
        show_percentages="index" # Calculate row-wise percentages
    )
    result = run(sample_df, step)
    results_df = result.data.set_index('region')

    # NA has 3 entries total (2 apple, 1 orange).
    # 'apple' should be 2/3, 'orange' should be 1/3.
    assert results_df.loc['NA', 'apple'] == pytest.approx(2/3)
    assert results_df.loc['NA', 'orange'] == pytest.approx(1/3)
    assert results_df.loc['NA', 'All'] == pytest.approx(1.0) # Row total must be 100%

# ==============================================================================
# 2. Interaction and Transformation Tests
# ==============================================================================

def test_crosstab_with_transformation(sample_df):
    """Tests that split_and_explode works correctly before crosstab."""
    step = CrosstabAnalysis(
        output_name="Region vs Tags (Exploded)",
        index_column="region",
        column_to_compare="tags",
        column_transformations=[
            ColumnTransformation(
                column_name="tags",
                transformations=[
                    Transformation(action="split_and_explode", params={"delimiter": ","})
                ]
            )
        ]
    )
    result = run(sample_df, step)
    results_df = result.data.set_index('region')

    # Manually calculate expected counts after exploding 'tags'
    # NA: A, B, C, C -> A:1, B:1, C:2
    # EU: B, A, C -> A:1, B:1, C:1
    # ASIA: A -> A:1
    assert results_df.loc['NA', 'A'] == 1
    assert results_df.loc['NA', 'B'] == 1
    assert results_df.loc['NA', 'C'] == 2
    assert results_df.loc['EU', 'A'] == 1
    assert results_df.loc['All', 'All'] == 8 # Total tags after explosion

def test_crosstab_with_filter(sample_df):
    """Tests that filtering is applied before calculation."""
    step = CrosstabAnalysis(
        output_name="EU Only",
        index_column="region",
        column_to_compare="product",
        filters=[Filter(column="region", operator="eq", value="EU")]
    )
    result = run(sample_df, step)
    results_df = result.data.set_index('region')

    # The result should only contain data for 'EU' and the 'All' row.
    assert 'NA' not in results_df.index
    assert 'ASIA' not in results_df.index
    assert results_df.loc['EU', 'apple'] == 1
    assert results_df.loc['EU', 'orange'] == 1
    assert results_df.loc['All', 'All'] == 2 # Grand total is only the filtered rows

# ==============================================================================
# 3. Edge Case Tests
# ==============================================================================

def test_crosstab_filter_yields_no_data(sample_df):
    """Tests graceful handling when a filter results in an empty DataFrame."""
    step = CrosstabAnalysis(
        output_name="No Data Test",
        index_column="region",
        column_to_compare="product",
        filters=[Filter(column="region", operator="eq", value="Antarctica")]
    )
    result = run(sample_df, step)
    
    assert isinstance(result, ReportBlock)
    # The resulting dataframe should be empty but have the correct placeholder columns
    assert result.data.empty
    assert list(result.data.columns) == ['Group', 'Data']
